version: '3.8'
services:
  # PostgreSQL with PostGIS
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: parking_spots_db
      POSTGRES_USER: parkuser
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    ports:
      - "32768:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 15s
      timeout: 20s
      retries: 5
      start_period: 10s

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # Spring Boot App
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  # Angular App
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./frontend:/project
      - /project/node_modules

volumes:
  db:
    driver: local