version: '3'
services:
  # PostgreSQL with PostGIS
  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: parking_spots_db
      POSTGRES_USER: parkuser
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "32768:5432"
    volumes:
      - db:/var/lib/postgresql/data

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # Spring Boot App
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
    - POSTGRES_DB=jdbc:postgresql://postgres:5432/parking_spots_db
    - POSTGRES_USER=parkuser

  # Angular App
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/project
      - /project/node_modules

volumes:
  db:
    driver: local